# Generated by Django 2.1.7 on 2019-04-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190419_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='UpdatedTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='UpdatedTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='UpdatedTime',
            field=models.DateTimeField(),
        ),
    ]
