# Generated by Django 2.1.7 on 2019-04-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190419_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitem',
            name='NGRate',
            field=models.FloatField(null=True),
        ),
    ]
